{"level":"info","message":"Unhandled Error Exception","meta":{"message":"Unhandled Error Exception","name":"Error","stack":"Error: Unhandled Error Exception\n    at Object.<anonymous> (C:\\Users\\wisam\\Desktop\\Courses Practice\\NodeJS\\11) Handling and logging errors\\vidly\\index.js:47:7)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49"},"timestamp":"2024-08-20T18:04:00.127Z"}
{"level":"info","message":"Unhandled Promise Rejection","meta":{"message":"Unhandled Promise Rejection","name":"Error","stack":"Error: Unhandled Promise Rejection\n    at Object.<anonymous> (C:\\Users\\wisam\\Desktop\\Courses Practice\\NodeJS\\11) Handling and logging errors\\vidly\\index.js:48:26)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49"},"timestamp":"2024-08-20T18:06:41.706Z"}
